name = "cf-url-shortener"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "URL_DB"
id = "your_kv_namespace_id_here"  # 替换为实际的 KV namespace ID
preview_id = "your_preview_kv_namespace_id_here"  # 替换为实际的 preview KV namespace ID

# Environment variables (configured in Cloudflare Dashboard)
# [vars]
# ADMIN_TOKEN = "your_secret_admin_token_change_this"
# BASE_URL = "https://link.xswweb.com"

# Production environment (optional)
[env.production]
name = "cf-url-shortener-prod"

