name = "cf-url-shortener"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "URL_DB"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# Environment variables (optional)
[vars]
ADMIN_TOKEN = "your_secret_admin_token_change_this"
BASE_URL = "https://link.xswweb.com"

# Production environment (optional)
[env.production]
name = "cf-url-shortener-prod"

